// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/(backstage)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)")>;
      $$route?: undefined;
    },
    {
      path: "/(content)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(content)")>;
      $$route?: undefined;
    },
    {
      path: "/about";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/about")>;
      $$route?: undefined;
    },
    {
      path: "/dev-test";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/dev-test")>;
      $$route?: undefined;
    },
    {
      path: "/(backstage)/backstage-template";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/backstage-template")>;
      $$route?: undefined;
    },
    {
      path: "/(content)/privacy-policy";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(content)/privacy-policy")>;
      $$route?: undefined;
    },
    {
      path: "/(content)/terms-of-service";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(content)/terms-of-service")>;
      $$route?: undefined;
    },
    {
      path: "/dev-test/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/dev-test/index")>;
      $$route?: undefined;
    },
    {
      path: "/dev-test/toast-demo";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/dev-test/toast-demo")>;
      $$route?: undefined;
    },
    {
      path: "/(backstage)/sign-out";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/sign-out")>;
      $$route?: undefined;
    },
    {
      path: "/*document_path";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...document_path]")>;
      $$route?: undefined;
    },
    {
      path: "/(backstage)/update-password";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/update-password")>;
      $$route?: undefined;
    },
    {
      path: "/(backstage)/forgot-password";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/forgot-password")>;
      $$route?: undefined;
    },
    {
      path: "/(backstage)/documents";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/documents")>;
      $$route?: undefined;
    },
    {
      path: "/(backstage)/sign-in";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/sign-in")>;
      $$route?: undefined;
    },
    {
      path: "/(backstage)/create-account";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/create-account")>;
      $$route?: undefined;
    },
    {
      path: "/dev-test/confirm-demo";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/dev-test/confirm-demo")>;
      $$route?: undefined;
    },
    {
      path: "/dev-test/save-as-demo";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/dev-test/save-as-demo")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/about";
      id: "/about";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/about")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/dev-test";
      id: "/dev-test";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/dev-test")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/dev-test/index")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/toast-demo";
          id: "/toast-demo";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/dev-test/toast-demo")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/confirm-demo";
          id: "/confirm-demo";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/dev-test/confirm-demo")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/save-as-demo";
          id: "/save-as-demo";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/dev-test/save-as-demo")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/";
      id: "/(content)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(content)")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/privacy-policy";
          id: "/privacy-policy";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(content)/privacy-policy")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/terms-of-service";
          id: "/terms-of-service";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(content)/terms-of-service")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/";
      id: "/(backstage)";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/sign-in";
          id: "/sign-in";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/sign-in")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/sign-out";
          id: "/sign-out";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/sign-out")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/documents";
          id: "/documents";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/documents")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/create-account";
          id: "/create-account";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/create-account")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/update-password";
          id: "/update-password";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/update-password")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/forgot-password";
          id: "/forgot-password";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/forgot-password")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/backstage-template";
          id: "/backstage-template";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/(backstage)/backstage-template")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/*document_path";
      id: "/*document_path";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...document_path]")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
